In [9]:
import numpy as np

#多次元配列のコードを記述
A = np.arange(6).reshape(3,2)
B = np.arange(8).reshape(2,4)

#行列の積を計算
total = np.dot(A,B)

#計算結果を記述
print(total)

#最大値を求める
print(f"最大値:{total.max()}")

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値:47
